version: '3.3'

services:
  app:
    build: .
    restart: always
    container_name: desafio-ezops
    ports:
      - '3000:3000'
    hostname: https://ec2-18-228-42-212.sa-east-1.compute.amazonaws.com
