# name: CI/CD counter app

# on:
#   push:
#     branches: [ master ]

# jobs:
#   Deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2 
#       - name: Deploy in EC2
#         env:
#             PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
#             HOSTNAME : ${{ secrets.HOSTNAME  }}
#             USER_NAME : ${{ secrets.USER_NAME  }}
            
#         run: |
#           ssh -o StrictHostKeyChecking=no -i ${PRIVATE_KEY} ${USER_NAME}@${HOSTNAME} '
          
#             #logged in ec2.
#             cd app/ezops-test-Matheus-Thurler
#             git checkout master &&
#             git pull origin master &&
#             docker-compose up --force-recreate --build -d

name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME  }}
        key: ${{ secrets.AWS_PRIVATE_KEY  }}
        username: ${{ secrets.USER_NAME  }}
        port: 22
        script: whoami
